### ISSUE TITLE
4 Contingency Tables

### ISSUE THREAD

**Issue by Chris21Arellano** [Chris21Arellano/QMB210-14Group1#6]
Create 4 contingencies based on the raw data to help create our project. Comment which you have completed

**Comment by 21-Aiden-N** [comment]
I have completed CT 1 Satisfaction by Garage

**Comment by JackHansen13** [comment]
I did two of the contingency tables with one of them comparing the year of students and the satisfaction level with parking. Then the second table was comparing parking by time of day to how often people have parking issues.

**Comment by Chris21Arellano** [comment]
I did the CT2 park availability by lateness
